DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS membership;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS conversations;

DROP SEQUENCE IF EXISTS user_id;
DROP SEQUENCE IF EXISTS conversation_id;
