DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS membership CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;

DROP SEQUENCE IF EXISTS user_id;
DROP SEQUENCE IF EXISTS conversation_id;

DROP FUNCTION IF EXISTS last_update;
DROP FUNCTION IF EXISTS last_update_conversations;
